import { Folder, Mail } from "./types";

export const mails: Mail[] = [
  {
    id: 1,
    from: "copstyle",
    address: "copstyle@naver.com",
    time: "2021-03-05 12:23:45",
    msg: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \n Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "Missing You",
    folder: "inbox",
    isRead: true,
  },
  {
    id: 2,
    from: "Test",
    address: "test@test.com",
    time: "2020-08-19 11:29:14",
    msg: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \n Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "Working Together",
    folder: "sent",
    isRead: true,
  },
  {
    id: 3,
    from: "Noel",
    address: "noel@test.com",
    time: "2018-07-03 22:18:35",
    msg: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \n Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "Why you so serious?",
    folder: "inbox",
    isRead: false,
  },
  {
    id: 4,
    from: "Ben",
    address: "ben@test.com",
    time: "2021-01-10 19:49:35",
    msg: "It is a long established fact that a isReader will be distracted by the isReadable content of a page when looking at its layout. \n\nThe point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like isReadable English. \nMany desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    title: "Learn more please!",
    folder: "trash",
    isRead: true,
  },

  {
    id: 10,
    from: "Christmas",
    address: "Christmas@test.com",
    time: "2019-07-05 12:10:14",
    msg: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \n Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    title: "Santa will be come!",
    folder: "inbox",
    isRead: true,
  },
  {
    id: 11,
    from: "Ken",
    address: "ken@test.com",
    time: "2018-12-24 11:29:27",
    msg: "It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "Santa will be come soon!",
    folder: "inbox",
    isRead: true,
  },
  {
    id: 12,
    from: "Americano",
    address: "americano@test.com",
    time: "2010-03-02 11:30:20",
    msg: "It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "Why americano is smell good?",
    folder: "inbox",
    isRead: false,
  },

  {
    id: 14,
    from: "silent",
    address: "silent@test.com",
    time: "2012-01-03 11:12:23",
    msg: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \n Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "Silent Hill is so scary!",
    folder: "inbox",
    isRead: true,
  },
  {
    id: 15,
    from: "Dev Yeong",
    address: "devyeong@test.com",
    time: "2021-04-10 12:13:34",
    msg: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \n Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "dev yeong is a front-end developer.",
    folder: "inbox",
    isRead: true,
  },
  {
    id: 5,
    from: "Slick",
    address: "slick@test.com",
    time: "2009-10-21 10:27:57",
    msg: "It is a long established fact that a isReader will be distracted by the isReadable content of a page when looking at its layout. \n\nThe point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like isReadable English. \nMany desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    title: "Join Our Team!",
    folder: "inbox",
    isRead: false,
  },
  {
    id: 6,
    from: "Position",
    address: "position@test.com",
    time: "2021-01-08 11:14:40",
    msg: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \n Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "Positioning something correctly!",
    folder: "trash",
    isRead: false,
  },
  {
    id: 7,
    from: "Float",
    address: "float@test.com",
    time: "2018-02-19 11:39:06",
    msg: "It is a long established fact that a isReader will be distracted by the isReadable content of a page when looking at its layout. \n\nThe point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like isReadable English. \nMany desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
    title: "Floating Left and Right!",
    folder: "inbox",
    isRead: false,
  },
  {
    id: 8,
    from: "flex",
    address: "flex@test.com",
    time: "2020-01-24 03:13:21",
    msg: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \n Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "Align Center Please!",
    folder: "trash",
    isRead: true,
  },
  {
    id: 9,
    from: "CockTail",
    address: "cocktail@test.com",
    time: "2011-11-01 11:22:13",
    msg: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \n Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "Your Friend is gone..",
    folder: "trash",
    isRead: true,
  },
  {
    id: 13,
    from: "peach",
    address: "peach@test.com",
    time: "2020-03-17 08:12:14",
    msg: "It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "peach is delicious!",
    folder: "inbox",
    isRead: true,
  },
  {
    id: 16,
    from: "Hi",
    address: "hi@test.com",
    time: "2014-02-21 04:10:44",
    msg: "It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "Hi!",
    folder: "inbox",
    isRead: false,
  },
  {
    id: 17,
    from: "Sayclub",
    address: "sayclub@test.com",
    time: "2016-03-21 03:24:49",
    msg: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \n Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "Cyworld is better?",
    folder: "inbox",
    isRead: true,
  },
  {
    id: 18,
    from: "mother",
    address: "mother@test.com",
    time: "2015-11-23 14:21:24",
    msg: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \n Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. \n It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    title: "Come Home!!!!",
    folder: "inbox",
    isRead: false,
  },
];
export const inbox: Folder = { id: 1, name: "Входящие", route: "/inbox" };
export const sent: Folder = { id: 2, name: "Отправленные", route: "/sent" };
export const drafts: Folder = { id: 3, name: "Черновики", route: "/drafts" };
export const spam: Folder = { id: 4, name: "Спам", route: "/spam" };
export const trash: Folder = { id: 5, name: "Удаленные", route: "/trash" };

export const folders: Folder[] = [inbox, sent, drafts, spam, trash];
